//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoursProjectClear.Base
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SaleComponentsEntities : DbContext
    {
        private static SaleComponentsEntities context;
        public static SaleComponentsEntities getContext()
        {
            if (context == null)
                context = new SaleComponentsEntities();
            return context;
        }
        public SaleComponentsEntities()
            : base("name=SaleComponentsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Basket> Basket { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Components> Components { get; set; }
        public virtual DbSet<Compos_Congsign> Compos_Congsign { get; set; }
        public virtual DbSet<Counterparties> Counterparties { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<List_Sale> List_Sale { get; set; }
        public virtual DbSet<Privileges> Privileges { get; set; }
        public virtual DbSet<Purchase> Purchase { get; set; }
        public virtual DbSet<Sale> Sale { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Staffs> Staffs { get; set; }
        public virtual DbSet<Sum> Sum { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Сonsignment> Сonsignment { get; set; }
    }
}
